name: Check renovatebot config

on:
  pull_request:

jobs:
  validate:
    name: Validate renovatebot config
    uses: HSLdevcom/jore4-tools/.github/workflows/shared-check-renovatebot-config.yml@shared-check-renovatebot-config-v1
    with:
      config_file_path: .github/renovate.json5
